//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ROIEntities : DbContext
    {
        public ROIEntities()
            : base("name=ROIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FinalSizeMapping> FinalSizeMapping { get; set; }
        public virtual DbSet<tNotReadyOrders> tNotReadyOrders { get; set; }
        public virtual DbSet<tOrders> tOrders { get; set; }
        public virtual DbSet<tOrderTharsternPushDetails> tOrderTharsternPushDetails { get; set; }
        public virtual DbSet<tSystemLog> tSystemLog { get; set; }
    }
}
