//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrderTharsternPushDetails
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public string DocumentId { get; set; }
        public string TharsternJson { get; set; }
        public Nullable<bool> PushedToTharstern { get; set; }
        public Nullable<System.DateTime> TharsternPushDatetime { get; set; }
        public string TharsternEstiamteNo { get; set; }
        public string Message { get; set; }
        public string TharsternJobNo { get; set; }
        public string JobDeliveryNote { get; set; }
        public string CustomerDeliveryNote { get; set; }
    
        public virtual tOrders tOrders { get; set; }
    }
}
